# Generated by Django 6.0.1 on 2026-01-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='content',
            field=models.TextField(default='Global Logistics Inc. is a premier logistics and shipping company with over 15 years of experience in providing reliable transportation solutions worldwide. We specialize in freight forwarding, warehousing, and supply chain management.'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='history',
            field=models.TextField(default='Founded in 2008, Global Logistics started as a small freight forwarding company. Through strategic partnerships and continuous innovation, we have grown into a global logistics provider serving clients in over 50 countries.'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission',
            field=models.TextField(default='To provide efficient, reliable, and cost-effective logistics solutions that exceed customer expectations while maintaining the highest standards of service and integrity.'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision',
            field=models.TextField(default="To be the world's most trusted logistics partner, connecting businesses globally through innovative supply chain solutions."),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(default='123 Logistics Street\nBusiness District\nNew York, NY 10001'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='Global Logistics Inc.', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(default='© 2024 Global Logistics Inc. All rights reserved.'),
        ),
    ]
