# Generated by Django 6.0.1 on 2026-01-13 21:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('sender_name', models.CharField(max_length=200)),
                ('receiver_name', models.CharField(max_length=200)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('receiver_email', models.EmailField(blank=True, max_length=254)),
                ('sender_phone', models.CharField(blank=True, max_length=20)),
                ('receiver_phone', models.CharField(blank=True, max_length=20)),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('package_description', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=10)),
                ('current_status', models.CharField(choices=[('registered', 'Registered'), ('in_transit', 'In Transit'), ('at_sorting', 'At Sorting Facility'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('on_hold', 'On Hold')], default='registered', max_length=50)),
                ('expected_delivery_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('in_transit', 'In Transit'), ('at_sorting', 'At Sorting Facility'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('on_hold', 'On Hold')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='shipments.shipment')),
            ],
            options={
                'verbose_name': 'Shipment Status Update',
                'verbose_name_plural': 'Shipment Status Updates',
                'ordering': ['-timestamp'],
            },
        ),
    ]
