# Generated by Django 6.0.1 on 2026-01-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='declared_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Declared value in USD', max_digits=12),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_proof',
            field=models.FileField(blank=True, null=True, upload_to='delivery_proofs/'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='dimensions',
            field=models.CharField(blank=True, help_text='L x W x H in cm', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='fragile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='hazardous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Insurance amount in USD', max_digits=12),
        ),
        migrations.AddField(
            model_name='shipment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Payment Pending'), ('partial', 'Partial Payment'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_type',
            field=models.CharField(choices=[('express', 'Express Delivery'), ('standard', 'Standard Delivery'), ('economy', 'Economy Delivery'), ('freight', 'Freight'), ('air_cargo', 'Air Cargo'), ('sea_cargo', 'Sea Cargo'), ('cold_chain', 'Cold Chain')], default='standard', max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='signature_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='temperature_range',
            field=models.CharField(blank=True, help_text='For cold chain shipments', max_length=50),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_code'], name='shipments_s_trackin_f1c65b_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['current_status'], name='shipments_s_current_c1528d_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['expected_delivery_date'], name='shipments_s_expecte_f3e96f_idx'),
        ),
    ]
