# Generated by Django 6.0.1 on 2026-03-11 09:42

import django.db.models.deletion
import shipments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipment_barcode_shipment_declared_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('BTC', 'Bitcoin'), ('USDT', 'USDT'), ('ETH', 'Ethereum')], default='USD', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('amount_in_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_proof', 'Awaiting Proof'), ('verified', 'Verified'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payer_name', models.CharField(blank=True, max_length=200)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('payer_phone', models.CharField(blank=True, max_length=20)),
                ('payment_proof', models.FileField(blank=True, help_text='Upload receipt, screenshot, or transaction proof', null=True, upload_to='payment_proofs/%Y/%m/%d/', validators=[shipments.models.validate_file_size, shipments.models.validate_document_extension])),
                ('proof_notes', models.TextField(blank=True, help_text='Additional notes about the proof')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes about this payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('method_type', models.CharField(choices=[('crypto', 'Cryptocurrency'), ('bank', 'Bank Transfer'), ('card', 'Credit/Debit Card'), ('mobile_money', 'Mobile Money'), ('cash', 'Cash')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Instructions for this payment method')),
                ('wallet_address', models.CharField(blank=True, help_text='BTC/USDT wallet address', max_length=255)),
                ('crypto_network', models.CharField(blank=True, help_text='e.g., Bitcoin, ERC20, TRC20', max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('iban', models.CharField(blank=True, max_length=50)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('routing_number', models.CharField(blank=True, max_length=50)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='payment_qrcodes/', validators=[shipments.models.validate_file_size, shipments.models.validate_image_extension])),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='carrier_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='carrier_service',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='customs_info',
            field=models.TextField(blank=True, help_text='Customs declaration information'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='goods_image',
            field=models.ImageField(blank=True, help_text='Picture of the goods being shipped', null=True, upload_to='shipment_goods/%Y/%m/%d/', validators=[shipments.models.validate_file_size, shipments.models.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_international',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='requires_dangerous_goods_declaration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tracking_url',
            field=models.URLField(blank=True, help_text='Custom tracking URL if different from internal'),
        ),
        migrations.AddField(
            model_name='shipmentstatus',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='shipmentstatus',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/', validators=[shipments.models.validate_file_size, shipments.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='delivery_proof',
            field=models.FileField(blank=True, null=True, upload_to='delivery_proofs/', validators=[shipments.models.validate_file_size, shipments.models.validate_document_extension]),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['payment_status'], name='shipments_s_payment_4b6da5_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='shipments.shipment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipments.paymentmethod'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='shipments_p_status_67dd6e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='shipments_p_transac_b98f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['shipment', 'status'], name='shipments_p_shipmen_e5aefd_idx'),
        ),
    ]
