# Generated by Django 6.0.1 on 2026-03-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_payment_paymentmethod_shipment_carrier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Taxes and duties', max_digits=10),
        ),
    ]
